apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postiz-app-secrets
spec:
  secretStoreRef:
    name: parameterstore
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /lobembe/postiz/database-url
    - secretKey: REDIS_URL
      remoteRef:
        key: /lobembe/postiz/redis-url
    - secretKey: JWT_SECRET
      remoteRef:
        key: /lobembe/postiz/jwt-secret
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: /lobembe/postiz/resend
