---

- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker.io
    - python3-pip
    - npm
    - pipx
- ansible.builtin.pip:
    name: docker
- community.general.pipx:
    name: runlike
- name: Ensure ubuntu is added to the docker group.
  user:
    name: "ubuntu"
    groups: docker
    append: true
- name: Reset ssh connection to apply user changes.
  meta: reset_connection