---

- community.general.snap:
    name:
      - btop

- name: Install and configure tailscale
  ansible.builtin.import_role:
    name: tailscale
  vars:
    verbose: true
    tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"