# First add CRDs with https://raw.githubusercontent.com/traefik/traefik/v2.9/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirecthttps          # middleware name
  namespace: kube-system                # <- replace with the namespace où tourne Traefik
spec:
  redirectScheme:
    scheme: https               # target scheme
    permanent: true
